### ISSUE TITLE
add more backbone

### ISSUE THREAD

**Issue by wannie163** [AlphaJia/pytorch-faster-rcnn#1]
Hi， thanks for your contribution， would you like to add more backbone like hrnet, some high resolution backbone network
   Thanks

**Comment by zhaodongxi** [comment]
from utils.anchor_utils import AnchorsGenerator, RegionProposalNetwork
cant find RegionProposalNetwork in anchor_utils.py,can you?

**Comment by AlphaJia** [comment]
> Hi， thanks for your contribution， would you like to add more backbone like hrnet, some high resolution backbone network
> Thanks

Thanks for your advice, hrnet has been added to the backbone.

**Comment by AlphaJia** [comment]
> from utils.anchor_utils import AnchorsGenerator, RegionProposalNetwork
> cant find RegionProposalNetwork in anchor_utils.py,can you?

Thanks, the bug has been fixed. Feel free to enjoy it. start if you like it
